version: '3.9'

services:
  frontend:
    restart: always
    build:
      context: frontend
      dockerfile: fe.Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - 93:3000
    environment:
      - API_URL=http://api.local:2027/backend/api
      - NEXT_PUBLIC_API_URL=http://api.local:2027/backend/api
      - NEXT_PUBLIC_APP_URL=http://api.local:2027
      - NEXTAUTH_URL=http://api.local:2027
      - NEXTAUTH_SECRET=/83vTMRaUYJObtDcbEa0AqhNXJ2gGVyNkol1nugIFi0=
    extra_hosts:
      - "api.local:host-gateway"
    tty: true
    command: >
      sh -c "
        if [ ! -d node_modules ]; then
          npm install;
        fi &&
        npm run dev"
  backend:
    ports:
      - 2032:80
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: laravel_backend
    working_dir: /var/www
    volumes:
      - ./backend/backend_sertifikasi:/var/www/html
    #command: bash -c "php artisan serve --host=0.0.0.0 --port=8000"

  nginx:
    image: nginx:alpine
    container_name: nginx_gateway
    ports:
      - "2031:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend